# Generated by Django 2.2.6 on 2019-10-07 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_fetcher', '0002_auto_20191007_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='response',
            field=models.TextField(null=True),
        ),
    ]
